const Stream = require("../models/Stream");
const { signStreamPath } = require("../utils/streamSigning");

const EMBED_PROVIDERS = new Set([
  "youtube",
  "vimeo",
  "dailymotion",
  "codespecters",
  "embed",
]);
const EXTERNAL_EMBED_PROVIDERS = new Set(["codespecters", "embed"]);
const LEGAL_PROVIDER_DEFAULTS = new Set([
  "youtube",
  "vimeo",
  "dailymotion",
  "codespecters",
  "embed",
  "archive",
]);

const isEmbedAutoFallbackEnabled = () =>
  String(process.env.EMBED_AUTO_FALLBACK || "true").toLowerCase() !== "false";

const normalizeSubtitleTracks = (tracks = []) =>
  (Array.isArray(tracks) ? tracks : [])
    .map((track) => ({
      label: String(track?.label || "").trim(),
      language: String(track?.language || "ar").trim() || "ar",
      url: String(track?.url || "").trim(),
      kind:
        String(track?.kind || "subtitles").trim().toLowerCase() === "captions"
          ? "captions"
          : "subtitles",
      isDefault: Boolean(track?.isDefault),
    }))
    .filter((track) => track.url);

const filterSourcesForUser = (sources = [], user = null) => {
  const isPremiumUser = user?.plan === "premium" || user?.role === "admin";

  return sources.filter((source) => {
    if (!source.isPremium) return true;
    return isPremiumUser;
  });
};

const buildStreamQuery = ({ mediaType, tmdbId, seasonNumber, episodeNumber }) => {
  const query = {
    mediaType,
    tmdbId: String(tmdbId),
  };

  if (mediaType === "movie") {
    query.seasonNumber = null;
    query.episodeNumber = null;
  }

  if (mediaType === "tv") {
    query.seasonNumber =
      seasonNumber !== undefined &&
      seasonNumber !== null &&
      seasonNumber !== ""
        ? Number(seasonNumber)
        : null;

    query.episodeNumber =
      episodeNumber !== undefined &&
      episodeNumber !== null &&
      episodeNumber !== ""
        ? Number(episodeNumber)
        : null;
  }

  return query;
};

const buildAutoEmbedSource = () => ({
  name: process.env.EMBED_SOURCE_NAME || "Codespecters",
  provider: process.env.EMBED_PROVIDER || "codespecters",
  playbackId: "",
  url: "",
  path: "",
  type: "embed",
  quality: "auto",
  language: "VO",
  isPremium: false,
  isLegal: true,
  subtitles: [],
});

const buildVirtualEmbedStream = ({
  mediaType,
  tmdbId,
  seasonNumber = null,
  episodeNumber = null,
}) => {
  if (!isEmbedAutoFallbackEnabled()) return null;

  return {
    _id: `auto-${mediaType}-${tmdbId}${
      mediaType === "tv" ? `-${seasonNumber}-${episodeNumber}` : ""
    }`,
    tmdbId: String(tmdbId),
    mediaType,
    seasonNumber: mediaType === "tv" ? Number(seasonNumber) : null,
    episodeNumber: mediaType === "tv" ? Number(episodeNumber) : null,
    title: "",
    poster: "",
    sources: [buildAutoEmbedSource()],
    isAutoGenerated: true,
  };
};

const inferSourceType = ({ provider, sourceType, url }) => {
  if (EMBED_PROVIDERS.has(provider)) {
    return "embed";
  }

  return sourceType || (String(url || "").includes(".m3u8") ? "hls" : "mp4");
};

const sanitizeSource = (source, index) => ({
  id: String(index),
  name:
    source.name ||
    `${source.quality || "Server"}${source.language ? ` - ${source.language}` : ""}`,
  quality: source.quality || "auto",
  language: source.language || "original",
  type: inferSourceType({
    provider: String(source.provider || "").trim().toLowerCase(),
    sourceType: source.type,
    url: source.url,
  }),
  provider: source.provider || "custom",
  isPremium: Boolean(source.isPremium),
  subtitles: normalizeSubtitleTracks(source.subtitles),
  isLegal:
    source.isLegal !== undefined && source.isLegal !== null
      ? Boolean(source.isLegal)
      : LEGAL_PROVIDER_DEFAULTS.has(
          String(source.provider || "").trim().toLowerCase()
        ),
});

const validateSources = (sources = []) => {
  if (!Array.isArray(sources) || sources.length === 0) {
    return "At least one source is required";
  }

  const invalidSource = sources.find((source) => {
    if (!source) return true;
    const provider = String(source.provider || "").trim().toLowerCase();
    if (
      !EXTERNAL_EMBED_PROVIDERS.has(provider) &&
      !String(source.playbackId || "").trim() &&
      !String(source.url || "").trim()
    ) {
      return true;
    }
    return false;
  });

  if (invalidSource) {
    return "Each source must include a playbackId or direct url, except configured embed providers";
  }

  const invalidSubtitle = sources.find((source) =>
    normalizeSubtitleTracks(source?.subtitles).some(
      (track) => !/^https?:\/\//i.test(track.url)
    )
  );

  if (invalidSubtitle) {
    return "Subtitle urls must be absolute http or https links";
  }

  return null;
};

const validateMediaPayload = ({
  mediaType,
  seasonNumber,
  episodeNumber,
}) => {
  if (!["movie", "tv"].includes(mediaType)) {
    return "Invalid mediaType";
  }

  if (
    mediaType === "tv" &&
    (seasonNumber === null ||
      seasonNumber === undefined ||
      seasonNumber === "" ||
      episodeNumber === null ||
      episodeNumber === undefined ||
      episodeNumber === "")
  ) {
    return "seasonNumber and episodeNumber are required for tv streams";
  }

  return null;
};

const signCustomUrl = ({ playbackId, path = "" }) => {
  const normalizedPath = path || `/videos/${playbackId}/master.m3u8`;
  return signStreamPath(normalizedPath);
};

const applyEmbedTemplate = (template, values) =>
  String(template || "")
    .replace(/:id\b/g, encodeURIComponent(values.id))
    .replace(/:tmdbId\b/g, encodeURIComponent(values.id))
    .replace(/:season\b/g, encodeURIComponent(values.season || ""))
    .replace(/:seasonNumber\b/g, encodeURIComponent(values.season || ""))
    .replace(/:episode\b/g, encodeURIComponent(values.episode || ""))
    .replace(/:episodeNumber\b/g, encodeURIComponent(values.episode || ""));

const appendEmbedApiKey = (url) => {
  const apiKey = String(process.env.EMBED_API_KEY || "").trim();
  if (!apiKey) return url;

  const separator = url.includes("?") ? "&" : "?";
  const keyParam = process.env.EMBED_API_KEY_PARAM || "api_key";
  return `${url}${separator}${encodeURIComponent(keyParam)}=${encodeURIComponent(
    apiKey
  )}`;
};

const buildExternalEmbedUrl = (source, context = {}) => {
  const base = String(process.env.EMBED_BASE || "").trim().replace(/\/+$/, "");
  if (!base) {
    throw new Error("EMBED_BASE missing");
  }

  const id = String(source?.playbackId || context.tmdbId || "").trim();
  if (!id) {
    throw new Error("Embed source requires playbackId or tmdbId");
  }

  const mediaType = context.mediaType || "movie";
  const customTemplate = String(source?.url || "").trim();
  const defaultTemplate =
    mediaType === "tv"
      ? process.env.EMBED_TV_PATH_TEMPLATE || "/embed/tv/:id/:season/:episode"
      : process.env.EMBED_MOVIE_PATH_TEMPLATE || "/embed/movie/:id";

  const rawUrl = applyEmbedTemplate(customTemplate || defaultTemplate, {
    id,
    season: context.seasonNumber,
    episode: context.episodeNumber,
  });

  const absoluteUrl = /^https?:\/\//i.test(rawUrl)
    ? rawUrl
    : `${base}/${rawUrl.replace(/^\/+/, "")}`;

  return appendEmbedApiKey(absoluteUrl);
};

const buildPlaybackUrl = (source, context = {}) => {
  const directUrl = String(source?.url || "").trim();
  const provider = String(source?.provider || "").trim().toLowerCase();

  if (directUrl && !EMBED_PROVIDERS.has(provider)) {
    return directUrl;
  }

  if (!source || !provider) {
    throw new Error("Invalid stream source");
  }

  if (provider === "custom") {
    return signCustomUrl({
      playbackId: source.playbackId,
      path: source.path,
    });
  }

  if (provider === "cloudflare") {
    const domain = process.env.CLOUDFLARE_STREAM_CUSTOMER_SUBDOMAIN;
    if (!domain) {
      throw new Error("CLOUDFLARE_STREAM_CUSTOMER_SUBDOMAIN missing");
    }

    return `https://${domain}/${source.playbackId}/manifest/video.m3u8`;
  }

  if (provider === "mux") {
    return `https://stream.mux.com/${source.playbackId}.m3u8`;
  }

  if (provider === "youtube") {
    const playbackId = String(source.playbackId || "").trim();
    if (!playbackId) {
      throw new Error("YouTube source requires playbackId");
    }
    return `https://www.youtube.com/embed/${playbackId}`;
  }

  if (provider === "vimeo") {
    const playbackId = String(source.playbackId || "").trim();
    if (!playbackId) {
      throw new Error("Vimeo source requires playbackId");
    }
    return `https://player.vimeo.com/video/${playbackId}`;
  }

  if (provider === "dailymotion") {
    const playbackId = String(source.playbackId || "").trim();
    if (!playbackId) {
      throw new Error("Dailymotion source requires playbackId");
    }
    return `https://www.dailymotion.com/embed/video/${playbackId}`;
  }

  if (EXTERNAL_EMBED_PROVIDERS.has(provider)) {
    return buildExternalEmbedUrl(source, context);
  }

  if (provider === "archive" || provider === "direct") {
    if (!directUrl) {
      throw new Error(`${provider} source requires direct url`);
    }
    return directUrl;
  }

  throw new Error("Unsupported stream provider");
};

const enrichSourceForPlayback = (source, context = {}) => {
  const url = buildPlaybackUrl(source, context);
  const provider = String(source?.provider || "").trim().toLowerCase();
  const inferredType = inferSourceType({
    provider,
    sourceType: source?.type,
    url,
  });

  return {
    id: "0",
    name:
      source?.name ||
      `${source?.quality || "Server"}${source?.language ? ` - ${source.language}` : ""}`,
    url,
    type: inferredType,
    quality: source?.quality || "auto",
    language: source?.language || "original",
    subtitles: normalizeSubtitleTracks(source?.subtitles),
    isPremium: Boolean(source?.isPremium),
    provider: source?.provider || "custom",
    isLegal:
      source?.isLegal !== undefined && source?.isLegal !== null
        ? Boolean(source.isLegal)
        : LEGAL_PROVIDER_DEFAULTS.has(provider),
  };
};

exports.getStreamByTmdb = async (req, res) => {
  try {
    const { mediaType, tmdbId } = req.params;
    const { seasonNumber, episodeNumber } = req.query;

    if (!["movie", "tv"].includes(mediaType)) {
      return res.status(400).json({
        success: false,
        message: "Invalid media type",
      });
    }

    const query = buildStreamQuery({
      mediaType,
      tmdbId,
      seasonNumber,
      episodeNumber,
    });

    const stream =
      (await Stream.findOne(query).lean()) ||
      buildVirtualEmbedStream({
        mediaType,
        tmdbId,
        seasonNumber,
        episodeNumber,
      });

    if (!stream) {
      return res.status(404).json({
        success: false,
        message: "No stream source found",
      });
    }

    const filteredSources = filterSourcesForUser(stream.sources, req.user);

    if (!filteredSources.length) {
      return res.status(403).json({
        success: false,
        message: "This content requires a premium account",
      });
    }

    return res.json({
      success: true,
      stream: {
        ...stream,
        sources: filteredSources.map(sanitizeSource),
      },
    });
  } catch (error) {
    return res.status(500).json({
      success: false,
      message: error.message || "Failed to fetch stream",
    });
  }
};

exports.getSignedPlayback = async (req, res) => {
  try {
    const { mediaType, tmdbId } = req.params;
    const { seasonNumber, episodeNumber, source = "0" } = req.query;

    if (!["movie", "tv"].includes(mediaType)) {
      return res.status(400).json({
        success: false,
        message: "Invalid media type",
      });
    }

    const query = buildStreamQuery({
      mediaType,
      tmdbId,
      seasonNumber,
      episodeNumber,
    });

    const stream =
      (await Stream.findOne(query).lean()) ||
      buildVirtualEmbedStream({
        mediaType,
        tmdbId,
        seasonNumber,
        episodeNumber,
      });

    if (!stream) {
      return res.status(404).json({
        success: false,
        message: "No stream source found",
      });
    }

    const filteredSources = filterSourcesForUser(stream.sources, req.user);

    if (!filteredSources.length) {
      return res.status(403).json({
        success: false,
        message: "This content requires a premium account",
      });
    }

    const requestedIndex = Number(source);
    const resolvedIndex =
      Number.isInteger(requestedIndex) && requestedIndex >= 0
        ? requestedIndex
        : 0;

    const selectedSource = filteredSources[resolvedIndex] || filteredSources[0];
    const finalIndex = filteredSources[resolvedIndex] ? resolvedIndex : 0;

    const playbackUrl = buildPlaybackUrl(selectedSource, {
      mediaType,
      tmdbId,
      seasonNumber,
      episodeNumber,
    });
    const provider = String(selectedSource.provider || "").trim().toLowerCase();
    const playbackType = inferSourceType({
      provider,
      sourceType: selectedSource.type,
      url: playbackUrl,
    });

    return res.json({
      success: true,
      playback: {
        id: String(finalIndex),
        name:
          selectedSource.name ||
          `${selectedSource.quality || "Server"}${
            selectedSource.language ? ` - ${selectedSource.language}` : ""
          }`,
        url: playbackUrl,
        type: playbackType,
        quality: selectedSource.quality || "auto",
        language: selectedSource.language || "original",
        subtitles: normalizeSubtitleTracks(selectedSource.subtitles),
        isPremium: Boolean(selectedSource.isPremium),
        provider: selectedSource.provider || "custom",
        isLegal:
          selectedSource.isLegal !== undefined && selectedSource.isLegal !== null
            ? Boolean(selectedSource.isLegal)
            : LEGAL_PROVIDER_DEFAULTS.has(provider),
      },
    });
  } catch (error) {
    return res.status(500).json({
      success: false,
      message: error.message || "Failed to generate playback url",
    });
  }
};

exports.createStream = async (req, res) => {
  try {
    const {
      tmdbId,
      mediaType,
      seasonNumber = null,
      episodeNumber = null,
      title,
      poster = "",
      sources = [],
    } = req.body;

    if (!tmdbId || !mediaType || !title) {
      return res.status(400).json({
        success: false,
        message: "tmdbId, mediaType and title are required",
      });
    }

    const mediaValidationError = validateMediaPayload({
      mediaType,
      seasonNumber,
      episodeNumber,
    });

    if (mediaValidationError) {
      return res.status(400).json({
        success: false,
        message: mediaValidationError,
      });
    }

    const sourcesValidationError = validateSources(sources);

    if (sourcesValidationError) {
      return res.status(400).json({
        success: false,
        message: sourcesValidationError,
      });
    }

    const payload = {
      tmdbId: String(tmdbId),
      mediaType,
      seasonNumber: mediaType === "tv" ? Number(seasonNumber) : null,
      episodeNumber: mediaType === "tv" ? Number(episodeNumber) : null,
      title,
      poster,
      sources,
    };

    const stream = await Stream.create(payload);

    return res.status(201).json({
      success: true,
      message: "Stream created successfully",
      stream,
    });
  } catch (error) {
    if (error.code === 11000) {
      return res.status(409).json({
        success: false,
        message: "A stream for this media already exists",
      });
    }

    return res.status(500).json({
      success: false,
      message: error.message || "Failed to create stream",
    });
  }
};

exports.updateStream = async (req, res) => {
  try {
    const { id } = req.params;
    const {
      tmdbId,
      mediaType,
      seasonNumber,
      episodeNumber,
      title,
      poster,
      sources,
    } = req.body;

    const stream = await Stream.findById(id);

    if (!stream) {
      return res.status(404).json({
        success: false,
        message: "Stream not found",
      });
    }

    const nextMediaType = mediaType !== undefined ? mediaType : stream.mediaType;
    const nextSeasonNumber =
      seasonNumber !== undefined ? seasonNumber : stream.seasonNumber;
    const nextEpisodeNumber =
      episodeNumber !== undefined ? episodeNumber : stream.episodeNumber;

    const mediaValidationError = validateMediaPayload({
      mediaType: nextMediaType,
      seasonNumber: nextSeasonNumber,
      episodeNumber: nextEpisodeNumber,
    });

    if (mediaValidationError) {
      return res.status(400).json({
        success: false,
        message: mediaValidationError,
      });
    }

    if (tmdbId !== undefined) stream.tmdbId = String(tmdbId);
    if (mediaType !== undefined) stream.mediaType = mediaType;
    if (title !== undefined) stream.title = title;
    if (poster !== undefined) stream.poster = poster;

    if (stream.mediaType === "movie") {
      stream.seasonNumber = null;
      stream.episodeNumber = null;
    } else {
      if (seasonNumber !== undefined) {
        stream.seasonNumber = Number(seasonNumber);
      }
      if (episodeNumber !== undefined) {
        stream.episodeNumber = Number(episodeNumber);
      }
    }

    if (sources !== undefined) {
      const sourcesValidationError = validateSources(sources);

      if (sourcesValidationError) {
        return res.status(400).json({
          success: false,
          message: sourcesValidationError,
        });
      }

      stream.sources = sources;
    }

    await stream.save();

    return res.json({
      success: true,
      message: "Stream updated successfully",
      stream,
    });
  } catch (error) {
    if (error.code === 11000) {
      return res.status(409).json({
        success: false,
        message: "Another stream with same media already exists",
      });
    }

    return res.status(500).json({
      success: false,
      message: error.message || "Failed to update stream",
    });
  }
};

exports.deleteStream = async (req, res) => {
  try {
    const { id } = req.params;

    const stream = await Stream.findByIdAndDelete(id);

    if (!stream) {
      return res.status(404).json({
        success: false,
        message: "Stream not found",
      });
    }

    return res.json({
      success: true,
      message: "Stream deleted successfully",
    });
  } catch (error) {
    return res.status(500).json({
      success: false,
      message: error.message || "Failed to delete stream",
    });
  }
};

exports.listStreams = async (req, res) => {
  try {
    const { mediaType, tmdbId } = req.query;

    const query = {};

    if (mediaType) query.mediaType = mediaType;
    if (tmdbId) query.tmdbId = String(tmdbId);

    const streams = await Stream.find(query).sort({ updatedAt: -1 }).lean();

    return res.json({
      success: true,
      streams,
    });
  } catch (error) {
    return res.status(500).json({
      success: false,
      message: error.message || "Failed to list streams",
    });
  }
};

exports.listLegalStreams = async (req, res) => {
  try {
    const { mediaType = "", provider = "" } = req.query;
    const normalizedProvider = String(provider || "").trim().toLowerCase();

    const query = {
      "sources.isPremium": false,
      "sources.isLegal": true,
    };

    if (mediaType) {
      query.mediaType = mediaType;
    }

    if (normalizedProvider) {
      query["sources.provider"] = normalizedProvider;
    }

    const streams = await Stream.find(query).sort({ updatedAt: -1 }).lean();

    const legalStreams = streams
      .map((stream) => {
        const legalSources = (stream.sources || [])
          .filter((source) => Boolean(source.isLegal) && !source.isPremium)
          .filter((source) =>
            normalizedProvider
              ? String(source.provider || "").trim().toLowerCase() ===
                normalizedProvider
              : true
          );

        if (!legalSources.length) return null;

        return {
          ...stream,
          sources: legalSources
            .map((source, index) => {
              try {
                return {
                  ...sanitizeSource(source, index),
                  playback: enrichSourceForPlayback(source, {
                    mediaType: stream.mediaType,
                    tmdbId: stream.tmdbId,
                    seasonNumber: stream.seasonNumber,
                    episodeNumber: stream.episodeNumber,
                  }),
                };
              } catch {
                return null;
              }
            })
            .filter(Boolean),
        };
      })
      .filter((entry) => entry && Array.isArray(entry.sources) && entry.sources.length);

    return res.json({
      success: true,
      streams: legalStreams,
      count: legalStreams.length,
    });
  } catch (error) {
    return res.status(500).json({
      success: false,
      message: error.message || "Failed to list legal streams",
    });
  }
};
